# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations

def set_pending_status(apps, schema_editor):
    WorkOrder = apps.get_model('workorders', 'workorders')
    WorkStatus = apps.get_model('workorders', 'Work_Status')
    
    # Try to get existing Pending status with ID 2 first
    try:
        pending_status = WorkStatus.objects.get(id=2, work_status='Pending')
    except WorkStatus.DoesNotExist:
        # If not found, get or create without enforcing ID
        pending_status, created = WorkStatus.objects.get_or_create(
            work_status='Pending',
            defaults={'id': 2}  # Try to use ID 2 if available
        )
    
    # Update all records with null work_status
    WorkOrder.objects.filter(work_status__isnull=True).update(work_status=pending_status)

class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_convert_workorder_history'),
    ]

    operations = [
        migrations.RunPython(set_pending_status),
    ]